Отчет по покупкам клиента в xlsx и ods
lazersib/multimag pull request #3
Opened 2019-10-30 11:33 UTC by magnatiwe

2019-11-25 17:37 UTC, lazersib commented on web/include/reports/agent_purchases_by_period.php
> -//	Copyright (C) 2005-2018, BlackLight, TND Team, http://tndproject.org
Этот файл не я делал - зачем мой ник тут?

2019-11-25 17:37 UTC, lazersib commented on web/include/reports/engine/BaseSheet.php
> +//	Copyright (C) 2005-2019, BlackLight, TND Team, http://tndproject.org
То же самое

2019-11-25 17:38 UTC, lazersib commented on web/include/reports/engine/Ods.php
> +//	Copyright (C) 2005-2019, BlackLight, TND Team, http://tndproject.org
И тут

2019-11-25 17:38 UTC, lazersib commented on web/include/reports/engine/Xls.php
> +//	Copyright (C) 2005-2019, BlackLight, TND Team, http://tndproject.org
И тут

2019-11-25 17:38 UTC, lazersib commented on web/include/reports/engine/Xlsx.php
> +//	Copyright (C) 2005-2019, BlackLight, TND Team, http://tndproject.org
И тут

2019-11-25 17:39 UTC, lazersib requested changes
Эти файлы не я создавал. И чужое автороство присваивать не буду :)

2019-11-25 17:40 UTC, lazersib requested changes
Композером не пользуемся, а в зависимостях куски от него есть. Нужно убрать.

2019-12-02 11:33 UTC, magnatiwe commented
там нет композера, только php файлы автозагрузки классов

2019-12-02 18:35 UTC, lazersib commented
Так я об этом и говорю - костыли.

2019-12-03 03:28 UTC, magnatiwe commented
Захардкодить библиотеку, подтянуть вручную все ее зависимости и зависимости зависимостей. Написать для них автозагрузку. Это не костыль?

2022-03-11 06:06 UTC, closed without merging