Badges
lazersib/multimag pull request #6
Opened 2019-11-27 07:07 UTC by magnatiwe

2019-12-01 18:50 UTC, lazersib requested changes
И подозреваю, что эти правки стоит делать вместе с параметрическим поиском по группе товаров, как на видео справа.
В ядре для этого есть все данные, нужно только витрину доделать.
Нужно обсудить.

2019-12-01 18:50 UTC, lazersib commented on web/include/vitrina/Badges.php
> +//	Copyright (C) 2005-2019, BlackLight, TND Team, http://tndproject.org
Почему я опять?

2019-12-01 18:50 UTC, lazersib commented on web/vitrina.php
> +	    Badges::productTypeFilter($group);
Давайте через конфиг, чтобы ничего никому не сломать в других скинах

2019-12-01 18:50 UTC, lazersib commented on web/include/vitrina/Badges.php
> +		$active_class =  $active ? 'btn-primary' : 'btn-light';
Почему нет этих крассов в дефолтном скине?

2019-12-02 11:38 UTC, magnatiwe commented on web/include/vitrina/Badges.php
> +		$active_class =  $active ? 'btn-primary' : 'btn-light';
А где посмотреть UI KIT?

2019-12-02 18:39 UTC, lazersib commented on web/include/vitrina/Badges.php
> +		$active_class =  $active ? 'btn-primary' : 'btn-light';
Нигде. Но возможно, в недалёком будущем стоит его сделать.

2022-03-11 06:06 UTC, closed without merging