Все предки документа (приход) в "Относится к"
lazersib/multimag pull request #9
Opened 2019-11-28 04:08 UTC by magnatiwe

2019-12-01 18:26 UTC, lazersib requested changes
Тут что-то странное происходит. В кассовом документе откуда-то склад появился.
Построение иерархии изменяется для отдельно взятого типа, а не для всех.
Непонятно, по какой задаче, непонятный комментарий коммита...

2019-12-01 18:26 UTC, lazersib commented on web/include/doc.credit.php
> +		if ($this->sklad_editor_enable) {
Тут что-то странное происходит. В кассовом документе откуда-то склад появился.

2019-12-02 11:26 UTC, magnatiwe commented on web/include/doc.credit.php
> +		if ($this->sklad_editor_enable) {
Попытаюсь описать задачу. В документах прихода показывать в  блоке "Относится к" не документ-предок, а заявку покупателя. Если ее нет, то реализацию.

Склад появился потому что не удалось нормально переопределить метод body базового класса, не стал тратить время на поиск причины, скопипастил код из базового. Так-то пожалуй стоило бы выкинуть из body построение блока "Относится к" и его уже переопределить.

2019-12-02 18:33 UTC, lazersib commented on web/include/doc.credit.php
> +		if ($this->sklad_editor_enable) {
Странная задача. Блок *относится к* именно что должен показывать предка, и во всех документах должно быть единообразно.
Изменение этого блока для какого-то конкретного документа - архитектурно криво.
И кроме этого, в новом редакторе документа, блок строящий иерархию, вообще о типе ничего не знает.
В таком виде - однозначно это не нужно.

2019-12-02 18:33 UTC, lazersib commented
Странная задача. Блок относится к именно что должен показывать предка, и во всех документах должно быть единообразно.
Изменение этого блока для какого-то конкретного документа - архитектурно криво.
И кроме этого, в новом редакторе документа, блок строящий иерархию, вообще о типе ничего не знает.
В таком виде - однозначно это не нужно.

2019-12-02 18:33 UTC, closed without merging